#	@(#)Makefile	5.2 (Berkeley) 05/09/91

SUBDIR=	arp bad144 cat cp dd disklabel dump ed fsck ftp ifconfig \
	init ls mkdir mknod mount mv netstat newfs ping restore rlogin \
	rm route rsh sh slattach stty sync tar telnet umount

.include <bsd.subdir.mk>

