#	@(#)Makefile	5.1 (Berkeley) 05/03/91

SUBDIR=	arp bad144 cat cp dd disklabel dump echo ed fsck ftp ifconfig \
	init ls mkdir mknod mount mv netstat newfs ping restore rlogin \
	rm route rsh sh slattach stty sync tar telnet umount

.include <bsd.subdir.mk>

