#!/bin/sh -
#
# Copyright (c) 1980 The Regents of the University of California.
# All rights reserved.
#
# %sccs.include.proprietary.sh%
#
#	@(#)runtest	5.2 (Berkeley) 04/12/91
#

sh testf77 tests | tee output/tests.res
