#	@(#)Makefile	5.6 (Berkeley) 05/11/90

PROG=	canfield
MAN6=	canfield.0
DPADD=	${LIBCURSES} ${LIBTERM} ${LIBCOMPAT}
LDADD=	-lcurses -ltermcap -lcompat
SUBDIR=	cfscores
HIDEGAME=hidegame

.include <bsd.prog.mk>
