#	@(#)Makefile.inc	5.1 (Berkeley) 06/26/92

SRCS+=	bcmp.c bcopy.c bzero.s ffs.c index.c memchr.c memcmp.c memset.c \
	rindex.c strcat.c strcmp.c strcpy.c strcspn.c strlen.c strncat.c \
	strncmp.c strncpy.c strpbrk.c strsep.c strspn.c strstr.c
