#	@(#)Makefile	5.2 (Berkeley) 05/11/90

# not currently compilable: pcc
SUBDIR=	bugfiler c2 comsat delivermail fingerd ftpd getNAME getty makekey \
	rexecd rlogind rshd talkd telnetd tftpd uucpd

.include <bsd.subdir.mk>
