#	@(#)Makefile	5.1 (Berkeley) 06/05/90

PROG=	exrecover
SRCS=	exrecover.c ex_extern.c
CFLAGS+=-I${.CURDIR}/..
.PATH:	${.CURDIR}/..
BINOWN=	root
BINDIR=	/usr/libexec
BINMODE=4555
NOMAN=	noman

.include <bsd.prog.mk>
