#	@(#)Makefile	5.4 (Berkeley) 05/12/91

PROG=	mk-amd-map
NOMAN=	true
CFLAGS+=-I${.CURDIR}/../include
CFLAGS+=-I${.CURDIR}/../rpcx
CFLAGS+=-I${.CURDIR}/../config
CFLAGS+=-DOS_HDR=\"os-bsd44.h\"

.include "../../Makefile.inc"
.include <bsd.prog.mk>
