#	@(#)Makefile	5.5 (Berkeley) 06/28/93

PROG=	mk-amd-map
CFLAGS+=-I${.CURDIR}/../include
CFLAGS+=-I${.CURDIR}/../rpcx
CFLAGS+=-I${.CURDIR}/../config
CFLAGS+=-DOS_HDR=\"os-bsd44.h\"

.include "../../Makefile.inc"
.include <bsd.prog.mk>
